/**
 * Author the npm bundled-cli launcher (`bin/<bin>.js`) at build time.
 *
 * Bundled-CLI consumers used to ship a templated launcher whose only
 * per-consumer inputs are the package name and the configured `targets`
 * list — both of which the engine has at plan time. Issue #299
 * absorbs that template into the engine: the build job invokes
 * `write-launcher` on the main row of every `kind = "npm" && build =
 * "bundled-cli"` package and the launcher is generated in place.
 *
 * Override semantics: existing `bin/<bin>.js` files are never
 * overwritten, and an existing `package.json#bin` field is left as-is.
 * Consumers who need a custom launcher commit it under the same path
 * and the workflow respects it.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, join, resolve } from 'node:path';

import { loadConfig, type NpmPackage } from './config.js';
import { normalizeBuild } from './handlers/npm-platform.js';
import { normalizeTarget } from './types.js';

export interface WriteLauncherOptions {
  /** Absolute path to the main package directory. */
  pkgDir: string;
  /** The main package's npm name (`pkg.npm ?? pkg.name`). Inlined into the
   *  `{name}` slot of `platformNameTemplate`; also keys `package.json#bin`. */
  npmName: string;
  /** CLI binary name (`pkg.bundle_cli.bin`). Names the launcher file and
   *  the published `bin` entry. */
  bin: string;
  /** Platform-package name template, e.g. `{name}-{triple}` or
   *  `@my-cli/cli-{triple}`. `{triple}` is preserved as a JS template
   *  substitution at install time; all other placeholders resolve here. */
  platformNameTemplate: string;
  /** Supported target triples. Becomes the `triples` table in the
   *  generated launcher's Node `${platform}-${arch}` lookup. */
  triples: readonly string[];
}

/**
 * Generate the launcher source for the given configuration.
 *
 * Exported only so test fixtures can pin the on-the-wire shape; the
 * build path goes through `writeLauncher` / `writeLauncherFromConfig`.
 */
export function generateLauncherSource(opts: WriteLauncherOptions): string {
  const { npmName, bin, platformNameTemplate, triples } = opts;
  // Resolve every template placeholder except {triple}, which stays as
  // a JS-template substitution. Pre-resolving here keeps the published
  // launcher dependency-free (no runtime read of the platform template).
  const partial = platformNameTemplate
    .replaceAll('{name}', npmName)
    .replaceAll('{scope}', extractScope(npmName))
    .replaceAll('{base}', extractBase(npmName))
    .replaceAll('{mode}', 'bundled-cli');

  const triplesTable = triples
    .map((triple) => {
      const key = nodePlatformKey(triple);
      return `  ${jsString(key)}: ${jsString(triple)},`;
    })
    .join('\n');

  // Backtick template + ${triple} substitution at install time keeps the
  // launcher's branching minimal: one Node platform-key lookup, one
  // require.resolve, one spawnSync. Same shape as the README example
  // bundled-cli consumers wrote by hand before #299.
  return [
    `#!/usr/bin/env node`,
    `// Generated by putitoutthere. Commit your own bin/${bin}.js to override.`,
    `const { spawnSync } = require('node:child_process');`,
    `const { platform, arch } = process;`,
    ``,
    `const triples = {`,
    triplesTable,
    `};`,
    ``,
    `const triple = triples[\`\${platform}-\${arch}\`];`,
    `if (!triple) {`,
    `  console.error(\`${bin}: unsupported platform \${platform}-\${arch}\`);`,
    `  process.exit(1);`,
    `}`,
    ``,
    `const pkg = \`${partial.replaceAll('{triple}', '${triple}')}\`;`,
    `const binary = require.resolve(\`\${pkg}/${bin}\${platform === 'win32' ? '.exe' : ''}\`);`,
    `const result = spawnSync(binary, process.argv.slice(2), { stdio: 'inherit' });`,
    `process.exit(result.status ?? 1);`,
    ``,
  ].join('\n');
}

/**
 * Author the launcher + `package.json#bin` entry for a bundled-cli npm
 * package. Idempotent: existing files / fields are left as-is so
 * consumers can override either piece independently.
 *
 * Returns the list of paths that were actually written.
 */
export function writeLauncher(opts: WriteLauncherOptions): string[] {
  const written: string[] = [];
  const launcherPath = join(opts.pkgDir, 'bin', `${opts.bin}.js`);
  // CodeQL TOCTOU: use `wx` (write-exclusive) rather than `existsSync`
  // precheck so the "absent only" guarantee is atomic. EEXIST means a
  // consumer-authored launcher (or a concurrent write) won this race —
  // exactly the override path we want to respect.
  mkdirSync(dirname(launcherPath), { recursive: true });
  try {
    writeFileSync(launcherPath, generateLauncherSource(opts), { encoding: 'utf8', flag: 'wx' });
    written.push(launcherPath);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'EEXIST') throw err;
  }

  const pkgJsonPath = join(opts.pkgDir, 'package.json');
  const raw = readFileSync(pkgJsonPath, 'utf8');
  const parsed = JSON.parse(raw) as Record<string, unknown>;
  if (parsed['bin'] === undefined) {
    parsed['bin'] = { [opts.bin]: `bin/${opts.bin}.js` };
    const indent = detectIndent(raw);
    const trailing = raw.endsWith('\n') ? '\n' : '';
    writeFileSync(pkgJsonPath, JSON.stringify(parsed, null, indent) + trailing, 'utf8');
    written.push(pkgJsonPath);
  }
  return written;
}

export interface WriteLauncherFromConfigOptions {
  /** Repo root — `${cwd}/putitoutthere.toml` is read to locate the package. */
  cwd: string;
  /** Package directory relative to `cwd` (or absolute). Matches against
   *  the config's `pkg.path`. */
  packagePath: string;
  /** Optional config path override (mirrors the global CLI flag). */
  configPath?: string;
}

/**
 * Config-driven entry point used by the CLI. Loads the config, finds
 * the `[[package]]` entry matching `packagePath`, derives the launcher
 * inputs, and delegates to `writeLauncher`. Non-npm packages and npm
 * packages without a bundled-cli build entry are no-ops — the build
 * job invokes this on every main row and only bundled-cli rows need
 * the launcher.
 */
export function writeLauncherFromConfig(
  opts: WriteLauncherFromConfigOptions,
): string[] {
  const cfg = loadConfig(opts.configPath ?? join(opts.cwd, 'putitoutthere.toml'));
  const absPkg = isAbsolute(opts.packagePath)
    ? opts.packagePath
    : resolve(opts.cwd, opts.packagePath);
  const pkg = cfg.packages.find(
    (p) => resolve(opts.cwd, p.path) === absPkg,
  );
  if (!pkg) {
    throw new Error(
      `write-launcher: no [[package]] entry with path "${opts.packagePath}" in ${opts.configPath ?? join(opts.cwd, 'putitoutthere.toml')}`,
    );
  }
  if (pkg.kind !== 'npm') return [];

  const npmPkg: NpmPackage = pkg;
  const buildEntries = normalizeBuild(npmPkg.build);
  const bundledCli = buildEntries.find((e) => e.mode === 'bundled-cli');
  if (!bundledCli) return [];
  // Schema (config.ts) guarantees `targets` is non-empty AND
  // `[package.bundle_cli]` is declared when at least one bundled-cli
  // entry exists in `build`; the non-null assertions document that
  // contract.
  const targets = npmPkg.targets!;
  const bundleCli = npmPkg.bundle_cli!;
  const triples = targets.map((t) => normalizeTarget(t).triple);
  const npmName = npmPkg.npm ?? npmPkg.name;
  return writeLauncher({
    pkgDir: resolve(opts.cwd, npmPkg.path),
    npmName,
    bin: bundleCli.bin,
    platformNameTemplate: bundledCli.name,
    triples,
  });
}

/* ----------------------------- internals ----------------------------- */

function extractScope(npmName: string): string {
  const m = /^@([^/]+)\/(.+)$/.exec(npmName);
  return m ? m[1]! : '';
}

function extractBase(npmName: string): string {
  const m = /^@([^/]+)\/(.+)$/.exec(npmName);
  return m ? m[2]! : npmName;
}

/**
 * Map a target triple (napi-rs short form or Rust target) to the Node
 * `${platform}-${arch}` lookup key used in the generated launcher's
 * `triples` table.
 *
 * Mirrors the TRIPLE_MAP in `src/handlers/npm-platform.ts`, but
 * collapses `os`/`cpu`/`libc` into the `<node-platform>-<node-arch>`
 * key Node exposes at install time. Unmapped triples throw — plan-
 * time guard (`assertTripleSupported`) already rejects them before the
 * matrix runs, so reaching the throw implies map drift between the
 * two files; the vocabulary matches `targetToOsCpu` so the drift is
 * obvious.
 */
export function nodePlatformKey(triple: string): string {
  const t = triple.toLowerCase();
  // napi-rs short form (`linux-x64-gnu`) already starts with the Node
  // platform + arch; lop off the libc suffix if present.
  for (const [prefix, key] of NAPI_PREFIXES) {
    if (t.startsWith(prefix)) return key;
  }
  // Rust target triples — explicit lookup.
  const rust = RUST_TARGET_KEYS[t];
  if (rust === undefined) {
    throw new Error(
      `write-launcher: target triple "${triple}" is not mapped to Node platform+arch`,
    );
  }
  return rust;
}

const NAPI_PREFIXES: readonly [string, string][] = [
  ['linux-x64', 'linux-x64'],
  ['linux-arm64', 'linux-arm64'],
  ['linux-arm-', 'linux-arm'],
  ['darwin-x64', 'darwin-x64'],
  ['darwin-arm64', 'darwin-arm64'],
  ['win32-x64', 'win32-x64'],
  ['win32-arm64', 'win32-arm64'],
];

const RUST_TARGET_KEYS: Record<string, string> = {
  'x86_64-unknown-linux-gnu': 'linux-x64',
  'x86_64-unknown-linux-musl': 'linux-x64',
  'aarch64-unknown-linux-gnu': 'linux-arm64',
  'aarch64-unknown-linux-musl': 'linux-arm64',
  'armv7-unknown-linux-gnueabihf': 'linux-arm',
  'armv7-unknown-linux-musleabihf': 'linux-arm',
  'x86_64-apple-darwin': 'darwin-x64',
  'aarch64-apple-darwin': 'darwin-arm64',
  'x86_64-pc-windows-msvc': 'win32-x64',
  'aarch64-pc-windows-msvc': 'win32-arm64',
};

function jsString(s: string): string {
  return `'${s.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;
}

/** 2 / 4 / tab. Defaults to 2 when undetectable. Mirrors npm.ts. */
export function detectIndent(source: string): number | string {
  const m = /^(?<indent>[ \t]+)"/m.exec(source);
  if (!m?.groups?.indent) return 2;
  const indent = m.groups.indent;
  if (indent.includes('\t')) return '\t';
  return indent.length;
}
